import type { Metadata } from "next";
import Appsidebar from "@/components/Sidebar/Appsidebar";
import NextTopLoader from "nextjs-toploader";
import BreadC from "@/components/Sidebar/BreadC";
import { Inter } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import "./globals.css";
import ReduxProvider from "@/redux/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Donezo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <NextTopLoader color="#000" showSpinner={false} />
          <div className="flex-grow  w-full">{children}</div>
        </ReduxProvider>
      </body>
    </html>
  );
}
